spring:
  # 배포 시에 환경변수에 DB 정보를 넣어줘서 서버 DB 사용
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/feedback?useSSL=false
    username: root
    password: 1234

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

  # Swagger 3.0.0 적용
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    cache: false

  devtools:
  # livereload 서버 켜기
    livereload:
      enabled: true
    remote:
      restart:
        # 원격 재시작 활성화
        enabled: true

# Jwt Secret Key
jwt:
  token:
    secret: secret123123.aa.bb.kk.yy.ee.oo.nn.gg

# 한글 깨지는 현상 방지
server:
  port: 8080
  servlet:
    encoding:
      force-response: true


